# Este tipo de Workflow ocorre apenas manualmente.
name: Workflow Concorrencia
run-name: Workflow Concorrencia ${{ github.run_number }}
on:
  workflow_dispatch:
    inputs:
      chave: 
        type: string
        default: pipeline-aula

concurrency:
  group: ${{ inputs.chave }}
  cancel-in-progress: true
  
jobs:
  exemplo-fluxo-execucao-01:
    runs-on: ubuntu-latest
    steps:
      - name: Execucao do job teste
        run: |
          sleep 120;
          echo "Action executada job 01"

  exemplo-fluxo-execucao-02:
    runs-on: ubuntu-latest
    needs: [exemplo-fluxo-execucao-01]
    steps:
      - name: Execucao do job teste
        run: |
          sleep 120;
          echo "Action executada job 02"          