name: Workflow Controle Condicional
on:
  push:

jobs:
  apenas-main:
    if: ${{  contains(github.ref, 'main') }}
    name: Este Job só executa na Branch Main
    runs-on: ubuntu-latest
    steps:
      - name: Executando na Main
        run: echo "Executando apenas na main"
    