name: Workflow Push - Branch
on:
  push:
    branches: ["main", "feature/*", "fix/*", "breaking/*"]
    
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Teste de commig por Push
        run: echo "Esta action só roda quando há pushh nos branchs configurados"
