name: Workflow Schedule
on:
    schedule:
        - cron: "*/2 * * * *"
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Teste para Cron a cada 2 min
        run: echo "Esta action roda a cada 2 minutos"