name: Workflow Controle Por Status
on:
  push:

jobs:
  action-com-erro:
    name: Action com erro
    runs-on: ubuntu-latest
    steps:
      - name: Echo Errado na Action
        run: ech "Echo foi escrito errado!"

      - name: Vai notificar se deu erro
        if: ${{ failure() }}
        run: echo "Deu erro na pipeline"

  job-com-erro:
    name: Job com erro
    runs-on: ubuntu-latest
    steps:
      - name: Echo Errado na Action
        run: ech "Echo foi escrito errado!"

  job-com-sucesso:
    needs: [job-com-erro]
    name: Sucesso
    runs-on: ubuntu-latest
    if: ${{ success() || failure() }}
    steps:
      - name: Este Job vai rodar mesmo que o dependente quebre
        run: echo "Echo foi escrito errado!"