name: Workflow Controle Por Status
on:
  push:

jobs:
  job-com-erro:
    name: Vai dar erro
    runs-on: ubuntu-latest
    steps:
      - name: Echo Errado
        run: ech "Echo foi escrito errado!"

      - name: Vai notificar se deu erro
        if: ${{ failure() }}
        run: echo "Deu erro na pipeline"